version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "15:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.2.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.0
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.0
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: eslint-config-marine
    versions:
    - 8.1.0
    - 8.3.0
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: ts-jest
    versions:
    - 26.5.3
